FROM node:22-alpine

RUN npm install -g pnpm@latest

WORKDIR /app

ARG DATABASE_URL

COPY ./packages ./packages

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json    ./turbo.json

COPY  ./apps/excelidraw_fe  ./apps/excelidraw_fe

RUN pnpm install
RUN pnpm run db:generate
RUN DATABASE_URL=${DATABASE_URL} pnpm run build

EXPOSE 3001

CMD ["pnpm", "run" , "start:frontend"]