FROM node:22-alpine

RUN npm install -g pnpm@latest

WORKDIR /app

COPY ./packages ./packages

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./package.json ./package.json
COPY ./turbo.json    ./turbo.json

COPY  ./apps/http-backend  ./apps/http-backend

RUN pnpm install
RUN pnpm run db:generate

EXPOSE 3002

CMD ["pnpm", "run" , "start:http-backend"]